logging:
  level:
    org:
      springframework:
        boot: INFO  # Ustawia poziom logowania dla Spring Boota na INFO
    com:
      bkleszcz:
        WordApp: INFO  # Ustawia poziom logowania dla Twojej aplikacji na DEBUG (dzięki temu będziesz miał więcej szczegółów)
        WordApp.db: DEBUG  # Ustawia poziom logowania dla zapytań związanych z bazą danych na DEBUG
    org.springframework.security: INFO  # Logowanie Spring Security, co pomoże zrozumieć problemy związane z 403 i bezpieczeństwem

spring:
  profiles:
    active: local  # Aktywuje profil lokalny (dla lokalnej konfiguracji)
  jpa:
    hibernate:
      ddl-auto: update  # Automatyczne aktualizowanie schematu bazy danych
server:
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
        same-site: lax